java -Xmx10G -jar aracne_LINUX.jar -e '/run/media/daniel/UBUNTU_SECOND/owncloud/TCGA-BRCA-DOCTORADO/2019/POST_CANDIDATURA/ANALISIS_ARACNE/PROCESAMIENTO_DATOS/MATRIZ_UNION_FINAL_MIT_ARACNE.txt' -o '/run/media/daniel/UBUNTU_SECOND/owncloud/TCGA-BRCA-DOCTORADO/2019/POST_CANDIDATURA/ANALISIS_ARACNE/ARACNE_AP_LINUX/RES_SIN_BOOTSTRAP' --tfs '/run/media/daniel/UBUNTU_SECOND/owncloud/TCGA-BRCA-DOCTORADO/2019/POST_CANDIDATURA/ANALISIS_ARACNE/PROCESAMIENTO_DATOS/mirnas.interesantes.txt' --pvalue 1E-8 --seed 1 --calculateThreshold --threads 11 --nodpi

for i in {1..100}
do
printf "%s\n" "$i"
java -Xmx10G -jar aracne_LINUX.jar -e '/run/media/daniel/UBUNTU_SECOND/owncloud/TCGA-BRCA-DOCTORADO/2019/POST_CANDIDATURA/ANALISIS_ARACNE/PROCESAMIENTO_DATOS/MATRIZ_UNION_FINAL_MIT_ARACNE.txt' -o '/run/media/daniel/UBUNTU_SECOND/owncloud/TCGA-BRCA-DOCTORADO/2019/POST_CANDIDATURA/ANALISIS_ARACNE/ARACNE_AP_LINUX/RES_SIN_BOOTSTRAP' --tfs '/run/media/daniel/UBUNTU_SECOND/owncloud/TCGA-BRCA-DOCTORADO/2019/POST_CANDIDATURA/ANALISIS_ARACNE/PROCESAMIENTO_DATOS/mirnas.interesantes.txt' --pvalue 1E-8 --seed $i --threads 11 --nodpi
done

java -Xmx10G -jar aracne_LINUX.jar -o '/run/media/daniel/UBUNTU_SECOND/owncloud/TCGA-BRCA-DOCTORADO/2019/POST_CANDIDATURA/ANALISIS_ARACNE/ARACNE_AP_LINUX/RES_SIN_BOOTSTRAP' --consolidate

